loglevel: info
syncinterval: 1h

mongo:
  uri: ${mongo_uri}
  database: ${mongo_database}
  collection: ${mongo_collection}
  username: ${mongo_username}
  password: ${mongo_password}

meilisearch:
    host: ${meili_url}
    key: ${meili_key}
    index: ${meili_index}

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0